# Generated by Django 5.1.7 on 2025-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividadesinactivo',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('cartaautorizacion', models.BinaryField()),
                ('institucion', models.CharField(max_length=255)),
                ('cartaaceptacioninst', models.BinaryField()),
                ('nombproyecto', models.CharField(max_length=255)),
                ('fechainicio', models.DateField()),
                ('fechafinal', models.DateField()),
                ('cartareincorporacion', models.BinaryField()),
            ],
            options={
                'db_table': 'actividadesInactivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_asesoria', models.BooleanField()),
                ('id_grado_asesoria', models.IntegerField()),
                ('id_fases_proyecto', models.IntegerField()),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('recursos', models.BooleanField()),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaExt',
            fields=[
                ('id_asesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('nombre_asesorado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asesoria_ext',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaInt',
            fields=[
                ('id_asesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('id_estudiante', models.IntegerField()),
            ],
            options={
                'db_table': 'asesoria_int',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=255)),
                ('id_plan_acad', models.IntegerField()),
                ('clave', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('id_tipo_capacitacion', models.IntegerField()),
                ('evento', models.CharField(max_length=30)),
                ('sede', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrasea',
            fields=[
                ('id_contrasena', models.IntegerField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contrasea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id_egresado', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('telefono_casa', models.CharField(max_length=10)),
                ('red_social', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'egresado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id_estancia', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_estancia', models.IntegerField()),
                ('id_ciudad', models.IntegerField()),
            ],
            options={
                'db_table': 'estancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_estatus', models.IntegerField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.BooleanField()),
                ('curp', models.CharField(max_length=20)),
                ('email_personal', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('discapacidad', models.BooleanField()),
                ('nombre_discapacidad', models.CharField(max_length=255)),
                ('hablante_indigena', models.BooleanField()),
                ('nombre_lengua', models.CharField(max_length=255)),
                ('iems_procedencia', models.CharField(max_length=255)),
                ('id_estatus', models.IntegerField()),
                ('promedio', models.FloatField()),
                ('id_pro_edu', models.IntegerField()),
                ('id_situacion', models.IntegerField()),
                ('generacion', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_estudios', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('grado_actual', models.CharField(max_length=255)),
                ('grado_estudiando', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('nombre_institucion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estudios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoAcad',
            fields=[
                ('id_evento_acad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('id_tipo_evento', models.IntegerField()),
                ('id_evento_subcategoria', models.IntegerField()),
                ('nombre_evento', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'evento_acad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoSubcategoria',
            fields=[
                ('id_evento_subcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('subcategoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'evento_subcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id_excursion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_excursion', models.BooleanField()),
                ('id_asignatura', models.IntegerField()),
                ('id_profesor', models.IntegerField()),
                ('destino', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('evidencias', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'excursion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaseProyecto',
            fields=[
                ('id_fase_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('fase', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fase_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id_grado_academico', models.IntegerField(primary_key=True, serialize=False)),
                ('grado_academico', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grado_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradoAsesoria',
            fields=[
                ('id_grado_asesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grado_asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.IntegerField(primary_key=True, serialize=False)),
                ('estudiante', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('acreditado', models.BooleanField()),
                ('asesorias', models.BooleanField()),
                ('certificacion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id_investigacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_producto', models.IntegerField()),
                ('isbn', models.CharField(max_length=255)),
                ('objeto_estudio', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('numero_edicion', models.CharField(max_length=255)),
                ('lugar_publicacion', models.CharField(max_length=255)),
                ('nombre_institucion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'investigacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombreTaller',
            fields=[
                ('id_nombre_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nombre_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAcad',
            fields=[
                ('id_plan_acad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pro_edu', models.IntegerField()),
                ('nombre_plan_acad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'plan_acad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticaProf',
            fields=[
                ('id_practica_prof', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('num_practicas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('empresa', models.CharField(max_length=255)),
                ('contratado', models.BooleanField()),
            ],
            options={
                'db_table': 'practica_prof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProEdu',
            fields=[
                ('id_pro_edu', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pro_edu', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pro_edu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('id_grado_academico', models.IntegerField()),
                ('id_pro_edu', models.IntegerField()),
                ('jefe_departamento', models.BooleanField()),
                ('id_tipo_profesor', models.IntegerField()),
                ('id_estudio', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('id_actividad', models.IntegerField()),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorEstancia',
            fields=[
                ('id_estancia', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('id_tipo_institucion', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('resultados', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'profesor_estancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorInvestigacion',
            fields=[
                ('id_investigacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'profesor_investigacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorProyecto',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('id_profesor', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'profesor_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('tipo_proyecto', models.IntegerField()),
                ('objetivo', models.CharField(max_length=255)),
                ('etapa', models.CharField(max_length=255)),
                ('financiamiento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('id_estado', models.IntegerField()),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('beneficiarios', models.CharField(max_length=255)),
                ('evidencias', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'servicio_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id_situacion', models.IntegerField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'situacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('tipo_taller', models.BooleanField()),
                ('id_nombre_taller', models.IntegerField()),
                ('representante', models.BooleanField()),
                ('selectivo', models.BooleanField()),
                ('acreditado', models.BooleanField()),
                ('club', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id_tipo_capacitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstancia',
            fields=[
                ('id_tipo_estancia', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_estancia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_estancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProfesor',
            fields=[
                ('id_tipo_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_profesor', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id_tipo_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuarios',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipousuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id_tutoria', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_tutoria', models.BooleanField()),
                ('id_profesor', models.IntegerField()),
                ('id_estudiante', models.IntegerField()),
                ('carta_asignacion', models.BinaryField()),
                ('motivo_tutoria', models.CharField(max_length=255)),
                ('atencion_seguimiento', models.CharField(max_length=255)),
                ('evidencia', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
                ('id_tipo_usuario', models.IntegerField()),
                ('id_departamento', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VinculacionAcad',
            fields=[
                ('id_vinculacion_acad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('acreditado', models.BooleanField()),
                ('beca', models.BooleanField()),
                ('nombre_beca', models.CharField(max_length=255)),
                ('tipo_vinculacion', models.BooleanField()),
                ('id_ciudad', models.IntegerField()),
            ],
            options={
                'db_table': 'vinculacion_acad',
                'managed': False,
            },
        ),
    ]
