# Generated by Django 5.1.7 on 2025-03-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividadesinactivo',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('cartaautorizacion', models.BinaryField()),
                ('institucion', models.CharField(max_length=255)),
                ('cartaaceptacioninst', models.BinaryField()),
                ('nombproyecto', models.CharField(max_length=255)),
                ('fechainicio', models.DateField()),
                ('fechafinal', models.DateField()),
                ('cartareincorporacion', models.BinaryField()),
            ],
            options={
                'db_table': 'actividadesInactivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_asesoria', models.BooleanField()),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('recursos', models.BooleanField()),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=30)),
                ('sede', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrasea',
            fields=[
                ('id_contrasena', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contrasea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id_egresado', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('telefono_casa', models.CharField(max_length=10)),
                ('red_social', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'egresado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id_estancia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('curp', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=60)),
                ('email_personal', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('iems_procedencia', models.CharField(max_length=255)),
                ('generacion', models.CharField(max_length=255)),
                ('fecha_ingreso', models.IntegerField()),
                ('discapacidad', models.BooleanField()),
                ('nombre_discapacidad', models.CharField(max_length=255)),
                ('motivo_situacion', models.CharField(max_length=255)),
                ('beca', models.BooleanField()),
                ('tipo_beca', models.CharField(max_length=255)),
                ('creditos', models.FloatField()),
                ('derecho_servicio_social', models.BooleanField()),
                ('fecha_nac', models.DateField()),
                ('sexo', models.BooleanField()),
                ('hablante_indigena', models.BooleanField()),
                ('nombre_lengua', models.CharField(max_length=255)),
                ('promedio', models.FloatField()),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_estudios', models.AutoField(primary_key=True, serialize=False)),
                ('grado_actual', models.CharField(max_length=255)),
                ('grado_estudiando', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('nombre_institucion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estudios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoAcad',
            fields=[
                ('id_evento_acad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'evento_acad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoSubcategoria',
            fields=[
                ('id_evento_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'evento_subcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id_excursion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_excursion', models.BooleanField()),
                ('destino', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('evidencias', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'excursion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaseProyecto',
            fields=[
                ('id_fase_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('fase', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fase_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id_grado_academico', models.AutoField(primary_key=True, serialize=False)),
                ('grado_academico', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grado_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradoAsesoria',
            fields=[
                ('id_grado_asesoria', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grado_asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('acreditado', models.BooleanField()),
                ('asesorias', models.BooleanField()),
                ('certificacion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id_investigacion', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=255)),
                ('objeto_estudio', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('numero_edicion', models.CharField(max_length=255)),
                ('lugar_publicacion', models.CharField(max_length=255)),
                ('nombre_institucion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'investigacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombreTaller',
            fields=[
                ('id_nombre_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nombre_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAcad',
            fields=[
                ('id_plan_acad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan_acad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'plan_acad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticaProf',
            fields=[
                ('id_practica_prof', models.AutoField(primary_key=True, serialize=False)),
                ('num_practica', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('empresa', models.CharField(max_length=255)),
                ('telefon_empresa', models.CharField(max_length=15)),
                ('contratado', models.BooleanField()),
            ],
            options={
                'db_table': 'practica_prof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProEdu',
            fields=[
                ('id_pro_edu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro_edu', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pro_edu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('jefe_departamento', models.BooleanField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('etapa', models.CharField(max_length=255)),
                ('financiamiento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('beneficiarios', models.CharField(max_length=255)),
                ('evidencias', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('horas_acreditdas', models.IntegerField()),
                ('horas_pendientes', models.IntegerField()),
                ('horas_proyecto', models.IntegerField()),
                ('fecha_ultimo_reporte', models.DateField()),
            ],
            options={
                'db_table': 'servicio_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id_situacion', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'situacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_taller', models.BooleanField()),
                ('representante', models.BooleanField()),
                ('selectivo', models.BooleanField()),
                ('acreditado', models.BooleanField()),
                ('club', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id_tipo_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstancia',
            fields=[
                ('id_tipo_estancia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estancia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_estancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id_tipo_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProfesor',
            fields=[
                ('id_tipo_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_profesor', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id_tipo_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuarios',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipousuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id_tutoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tutoria', models.BooleanField()),
                ('carta_asignacion', models.BinaryField()),
                ('motivo_tutoria', models.CharField(max_length=255)),
                ('atencion_seguimiento', models.CharField(max_length=255)),
                ('evidencia', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VinculacionAcad',
            fields=[
                ('id_vinculacion_acad', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('acreditado', models.BooleanField()),
                ('beca', models.BooleanField()),
                ('nombre_beca', models.CharField(max_length=255)),
                ('tipo_vinculacion', models.BooleanField()),
            ],
            options={
                'db_table': 'vinculacion_acad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaExt',
            fields=[
                ('id_asesoria', models.OneToOneField(db_column='id_asesoria', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moduloetl.asesoria')),
                ('nombre_asesorado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asesoria_ext',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaInt',
            fields=[
                ('id_asesoria', models.OneToOneField(db_column='id_asesoria', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moduloetl.asesoria')),
            ],
            options={
                'db_table': 'asesoria_int',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorEstancia',
            fields=[
                ('id_estancia', models.OneToOneField(db_column='id_estancia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moduloetl.estancia')),
                ('id_tipo_institucion', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('resultados', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'profesor_estancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorInvestigacion',
            fields=[
                ('id_investigacion', models.OneToOneField(db_column='id_investigacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moduloetl.investigacion')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'profesor_investigacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorProyecto',
            fields=[
                ('id_proyecto', models.OneToOneField(db_column='id_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moduloetl.proyecto')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'profesor_proyecto',
                'managed': False,
            },
        ),
    ]
