# Generated by Django 5.1.7 on 2025-03-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloetl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contrasea',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='egresado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estadoservicio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estatus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nombretaller',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='planacad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proedu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='serviciosocial',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='situacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoingreso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipousuarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tutoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vinculacionacad',
            options={'managed': True},
        ),
    ]
