# Generated by Django 5.1.7 on 2025-03-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloetl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contrasea',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='practicaprof',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipousuarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tutoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vinculacionacad',
            options={'managed': True},
        ),
    ]
