# Generated by Django 5.1.7 on 2025-03-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloetl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombretaller',
            options={'managed': True},
        ),
    ]
