# Generated by Django 5.1.7 on 2025-03-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloetl', '0002_alter_nombretaller_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombretaller',
            name='id_nombre_taller',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
