# Generated by Django 5.1.7 on 2025-03-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloetl', '0003_alter_nombretaller_id_nombre_taller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombretaller',
            options={'managed': False},
        ),
    ]
